import { NextRequest, NextResponse } from 'next/server';
import { getStoryById, getIPById } from '@/lib/db/fileDb.server';
import { StoryboardFrame } from '@/types';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { storyId, customStory } = body;

    let story = customStory;
    if (!story && storyId) {
      story = getStoryById(storyId);
    }

    if (!story) {
      return NextResponse.json({ success: false, error: 'Story data is required' }, { status: 400 });
    }

    const ip = getIPById(story.ipId);

    // Format full markdown export bundle
    const markdownContent = `# ${story.xhsSelectedTitle || story.title}
${ip ? `\n> **原创 IP**: ${ip.name} (${ip.archetype}) | **画风**: ${ip.stylePreset}\n` : ''}
## 📱 小红书发布正文 (Copyable Post)
${story.xhsContent}

## 🏷️ 推荐话题标签 (Hashtags)
${story.xhsTags.join(' ')}

## 🎨 视觉分镜清单 (Visual Storyboard Index)
${story.frames.map((f: StoryboardFrame, idx: number) => `
### [Frame ${idx + 1}] ${f.title} ${f.isCover ? '🌟 (Cover)' : ''}
- 画面描述: ${f.visualPrompt}
- 英文 Prompt: ${f.visualPromptEn}
- 对白/旁白: ${f.dialogue || f.narration}
- 图片地址: ${f.imageUrl}
`).join('\n')}

---
Generated by IP Helper Studio
`;

    return NextResponse.json({
      success: true,
      exportData: {
        title: story.xhsSelectedTitle || story.title,
        content: story.xhsContent,
        tags: story.xhsTags,
        markdownText: markdownContent,
        images: story.frames.map((f: StoryboardFrame, idx: number) => ({
          filename: `0${idx + 1}_${f.isCover ? 'cover_' : ''}frame_${f.frameNumber}.jpg`,
          url: f.imageUrl,
          title: f.title
        }))
      }
    });
  } catch (error: unknown) {
    const errorMsg = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ success: false, error: errorMsg }, { status: 500 });
  }
}
